### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by xyproto** [riscvarchive/riscv-fesvr#65]
fesvr is now packaged for Arch Linux.

Could you please make a release tag, just to have a version number for the package?

https://www.archlinux.org/packages/community/x86_64/fesvr/

**Comment by aswaterman** [comment]
@palmer-dabbelt can you propose how we should version/release this package and take care of this? See also https://github.com/riscv/riscv-isa-sim/issues/290

**Comment by aswaterman** [comment]
Consequent to your request, we are deprecating this repository and merging it into the https://github.com/riscv/riscv-isa-sim repo, so there will only be one thing to version.

**Comment by gurjeet** [comment]
@aswaterman I think it would be prudent to mark this repository as [`Archived`](https://help.github.com/en/articles/about-archiving-repositories)
